# -*- coding: utf-8 -*-
"""CatTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSxzMjIEOf9CFezFM8Qa1fuhxssP4POs
"""

import random
import matplotlib.pyplot as mp
import time

class VirtualFuelSensor:
    def connect(self): print("001 - Connection Acknowledged") #001
    def get_status(self): print("101 - Status ok") #010
    def get_fuel_level(self): return random.randint(0, 100) #011
    def disconnect(self): print("100 - Session Ended") #100

def run_session():
    device = VirtualFuelSensor()
    fuel_levels, timestamps = [], []

    device.connect()
    device.get_status()

    for i in range(5):  #recording 5 randomly generated fuel levels
        fuel = device.get_fuel_level()
        print("011 (Fuel Level:" + str(fuel) + ")")
        fuel_levels.append(fuel)
        timestamps.append(time.time())
        time.sleep(1)

    device.disconnect()

    # Ploting fuel levels
    mp.plot(timestamps, fuel_levels, marker='o')
    mp.xlabel("Time (s)")
    mp.ylabel("Fuel Level")
    mp.title("Fuel Level Over Time")
    mp.show()

if __name__ == "__main__":
    run_session()